import CitiesProvider from "./citiesProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex min-h-screen flex-col p-4 bg-gray-950 text-slate-200">
          <CitiesProvider>{children}</CitiesProvider>
        </div>
      </body>
    </html>
  );
}
